### ISSUE TITLE
大神您好，插件很好用，请问可否转载到论坛？

### ISSUE THREAD

**Issue by shuaiger** [bit3725/homeassistant-mi-water-purifier#1]
大神您好，测试了下，您的插件非常好用，请问可否转载到国内Home Assistant论坛（bbs.hassbian.com），让更多人看到并用上您的插件？

非常感谢！

**Comment by bit3725** [comment]
可以：）
我没有论坛账号，您可以直接发帖。

**Comment by shuaiger** [comment]
多谢多谢，啥时注册了 论坛@一下 @jones 有贵宾礼遇~

**Comment by bit3725** [comment]
@shuaiger 已注册

**Comment by shuaiger** [comment]
请告知用户名

**Comment by bit3725** [comment]
@shuaiger bit3725

**Comment by shuaiger** [comment]
ok 已加最高权限
