### ISSUE TITLE
hass.io not working component

### ISSUE THREAD

**Issue by freenetwork** [bit3725/homeassistant-mi-water-purifier#5]
hass.io (Home Assistant 0.92.2) already not working component
![Снимок экрана 2019-05-06 в 0 31 24](https://user-images.githubusercontent.com/3347236/57197867-526a8180-6f96-11e9-90a3-6bc7cc85fe82.png)
![Снимок экрана 2019-05-06 в 0 32 04](https://user-images.githubusercontent.com/3347236/57197872-644c2480-6f96-11e9-860a-10755481d32f.png)
![Снимок экрана 2019-05-06 в 0 34 24](https://user-images.githubusercontent.com/3347236/57197900-bb51f980-6f96-11e9-8882-b914f72c297b.png)

**Comment by bit3725** [comment]
@freenetwork I just updated it to support HA 0.88+ version, you can try it again.
